function Protein = NETD_Fragments(strProteinSequence);

clc
% Protein.sequence = strProteinSequence;
% Protein.sequence = 'MAPNAS';
Protein.sequence = 'MAPNASCLCVHVRSEEWDLMTFDANPYDSVKKIKEHVRSKTKVPVQDQVLLLGSKILKPRRSLSSYGIDKEKTIHLTLKVVKPSDEELPLFLVESGDEAKRHLLQVRRSSSVAQVKAMIETKTGIIPETQIVTCNGKRLEDGKMMADYGIRKGNLLFLACYCIGG';
Protein.MW= 0;
Protein.LeftIon = zeros(length(Protein.sequence),1); %Molecular weight of the left ion generated by fragmentation
Protein.RightIon = zeros(length(Protein.sequence),1);

for i=1:length(Protein.sequence) %for loop running for the length of the protein sequence
    
    if i == 1
        Protein.LeftIon(i) = GetMWofAA(Protein.sequence(i)));
    else
        Protein.LeftIon(i) = (Protein.LeftIon(i-1) + GetMWofAA(Protein.sequence(i))) ;
        
    end
end

Protein.MW= Protein.LeftIon(length(Protein.sequence)); % last Leftion will be the MW

% calculate right ions by subtracting left ions from MW of protein
for i= 1: numel(Protein.LeftIon)
    Protein.RightIon(i) = Protein.MW - Protein.LeftIon(i);
end

% to check sum of ions is right

for i= 1: numel(Protein.LeftIon)
    Protein.RightIon(i)+Protein.LeftIon(i)
end

Protein.LeftIon(length(Protein.sequence))= []; % as this will be the MW of protein
Protein.RightIon(length(Protein.sequence))= []; % as this will be zero 

% netd

Protein.LeftIon= Protein.LeftIon - 28.01804;


end
%http://www.matrixscience.com/help/fragmentation_help.html