%CalculateMWofCIDFragments(strProteinSequence, iPostion, strFragmentationMethod)
clc
clear all

mzXMLStruct=mzxmlread('result.mzXML');


Protein.sequence = 'MAPNASCLCVHVRSEEWDLMTFDANPYDSVKKIKEHVRSKTKVPVQDQVLLLGSKILKPRRSLSSYGIDKEKTIHLTLKVVKPSDEELPLFLVESGDEAKRHLLQVRRSSSVAQVKAMIETKTGIIPETQIVTCNGKRLEDGKMMADYGIRKGNLLFLACYCIGG';
Protein.MW= 0;
Protein.leftion = zeros(size(Protein.sequence,2),1);%Molecular weight of the left ion generated by fragmentation
%Protein.MS= zeros(size((mzXMLStruct.scan),1));
%Protein.Intensity= zeros(size((mzXMLStruct.scan),1));
%for i = 1:size((mzXMLStruct.scan),1)
    %Protein.MS(i)= mzXMLStruct.scan(i,1).basePeakMz;
    %Protein.Intenisty(i)= mzXMLStruct.scan(i,1).basePeakIntensity;
%end

Protein.immonium = zeros(size(Protein.sequence,2),1);
for i = 1:4
    Protein.MS(i,1)= mzXMLStruct.scan(i,1).basePeakMz;
    Protein.Intenisty(i,1)= mzXMLStruct.scan(i,1).basePeakIntensity;
end
for i=1:size(Protein.sequence,2) %for loop running for the length of the protein sequence
    Protein.immonium(i)= GetMWofAA(Protein.sequence(i));
    if i == 1
        Protein.leftion(i) = (Protein.leftion(i) + GetMWofAA(Protein.sequence(i)));
        
    else 
    Protein.leftion(i) = (Protein.leftion(i-1) + GetMWofAA(Protein.sequence(i))) ;
    
    end
end
Protein.MW= Protein.leftion(size(Protein.sequence,2)) ;
Protein.immonium= Protein.immonium - 28.0101;
Protein.immonium(size(Protein.sequence,2))= [];
Protein.leftion_b= Protein.leftion + 1.00794;
Protein.leftion_b(size(Protein.sequence,2))= [];
Protein.leftion_a= Protein.leftion - 28.01804;
Protein.leftion_a(size(Protein.sequence,2))= [];


%http://www.matrixscience.com/help/fragmentation_help.html