%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%           LUMSProT: A MATLAB Toolbox for Top-down Proteomics     %
%                            Version 1.0.0                         %
%        Copyright (c) Biomedical Informatics Research Laboratory, %
%          Lahore University of Management Sciences Lahore (LUMS), %
%                           Pakistan.                              %
%                    (http://birl.lums.edu.pk) 	                   %
%                     (safee.ullah@gmail.com)                      %
%                    Last Modified on: 4-May-2016                  %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
CalculateMWofCIDFragments(strProteinSequence)

Protein.sequence = strProteinSequence;
Protein.MW= 0;
Protein.leftion = zeros(size(Protein.sequence,2),1);%Molecular weight of the left ion generated by fragmentation

Protein.immonium = zeros(size(Protein.sequence,2),1);
for i = 1:4
    Protein.MS(i,1)= mzXMLStruct.scan(i,1).basePeakMz;
    Protein.Intenisty(i,1)= mzXMLStruct.scan(i,1).basePeakIntensity;
end
for i=1:size(Protein.sequence,2) %for loop running for the length of the protein sequence
    Protein.immonium(i)= GetMWofAA(Protein.sequence(i));
    if i == 1
        Protein.leftion(i) = (Protein.leftion(i) + GetMWofAA(Protein.sequence(i)));
        
    else 
    Protein.leftion(i) = (Protein.leftion(i-1) + GetMWofAA(Protein.sequence(i))) ;
    
    end
end
Protein.MW= Protein.leftion(size(Protein.sequence,2)) ;
Protein.immonium= Protein.immonium - 28.0101;
Protein.immonium(size(Protein.sequence,2))= [];
Protein.leftion_b= Protein.leftion + 1.00794;
Protein.leftion_b(size(Protein.sequence,2))= [];
Protein.leftion_a= Protein.leftion - 28.01804;
Protein.leftion_a(size(Protein.sequence,2))= [];


%http://www.matrixscience.com/help/fragmentation_help.html
